# dhcpd.conf
option domain-name "lexlegal.com";
option domain-name-servers ns1.lexlegal.com;

default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;
authoritative;

#	FAILOVER
# PRIMARY:
failover peer "lex.fallos" {
 primary;
 address 10.0.0.10;
 port 647;
 peer address 10.0.0.11;
 peer port 647;
 max-response-delay 30;
 max-unacked-updates 10;
 load balance max seconds 3;
 mclt 3600;
 split 128;
}

# SUBNET-0
subnet 10.0.0.0 netmask 255.255.255.0{ 
 pool{
 range 10.0.0.100 10.0.0.200;
 failover peer "lex.fallos";
 option routers 10.0.0.1;
 }
}

# SUBNET-10
subnet 10.0.10.0 netmask 255.255.255.0{ 
 pool{
 range 10.0.10.100 10.0.10.200;
 failover peer "lex.fallos";
 option routers 10.0.10.1;
 }
}

# SUBNET-20
subnet 10.0.20.0 netmask 255.255.255.0{ 
 pool{
 range 10.0.20.100 10.0.20.200;
 failover peer "lex.fallos";
 option routers 10.0.20.1;
 }
}


# SUBNET-30
subnet 10.0.30.0 netmask 255.255.255.0{ 
 pool{
 range 10.0.30.100 10.0.30.200;
 failover peer "lex.fallos";
 option routers 10.0.30.1;
 }
}
