option domain-name "lexlegal.com";
option domain-name-servers ns1.lexlegal.com;

default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;

# FAILOVER - SECONDARY
failover peer "lex.fallos" {
    secondary;
    address 10.0.0.11;
    port 647;
    peer address 10.0.0.10;
    peer port 647;
    max-response-delay 30;
    max-unacked-updates 10;
    mclt 3600;
    load balance max seconds 3;
}

subnet 10.0.0.0 netmask 255.255.255.0 {
    pool {
        range 10.0.0.20 10.0.0.99;
        failover peer "lex.fallos";
        option routers 10.0.0.1;
    }
}

subnet 10.0.10.0 netmask 255.255.255.0 {
    pool {
        range 10.0.10.20 10.0.10.99;
        failover peer "lex.fallos";
        option routers 10.0.10.1;
    }
}

subnet 10.0.20.0 netmask 255.255.255.0 {
    pool {
        range 10.0.20.20 10.0.20.99;
        failover peer "lex.fallos";
        option routers 10.0.20.1;
    }
}

subnet 10.0.30.0 netmask 255.255.255.0 {
    pool {
        range 10.0.30.20 10.0.30.99;
        failover peer "lex.fallos";
        option routers 10.0.30.1;
    }
}
